### ISSUE TITLE
Duplicate Tab to include History/Cache of Current Tab?

### ISSUE THREAD

**Issue by thefferon** [reaperhulk/Tab-Duplicator#2]
Hi,

Duplicating tabs is awesome - thank you! But what I would like to happen when you duplicate a tab is to duplicate it in context - it shoudl include the entire browsing history for that tab as well. (All tab duplicator extensions I've seen so far only port the current page to the new tab, so you can't hit "back" to see the prior page.

Is it possible to do this?

Thanks,
Tim

**Comment by reaperhulk** [comment]
Unfortunately duplicating browsing history requires the ability to manipulate the history object via JS.  I'm fairly sure Safari's extensions do not have this privilege level, but I'll look into it!

**Comment by reaperhulk** [comment]
Yeah, even with the new HTML5 pushState methods available to the history object this can't be done.  Apple needs to lift the security restrictions on requiring the same domain when pushing items onto the history object while operating in the extension namespace/scope.
