### ISSUE TITLE
No contextual menu item in Safari 5.1.7

### ISSUE THREAD

**Issue by ghost** [reaperhulk/Tab-Duplicator#3]
The only way to duplicate a tab with Tab Duplicator in 5.1.7 is to click the menu bar button. No context menu item is available.

**Comment by ghost** [comment]
Never mind — the contextual menu item appears when you right-click on page itself, not the tab in the tab bar.

**Comment by reaperhulk** [comment]
I'll take a look when I get a chance. Definitely a bug I want to fix. Thanks for the report! 

-Paul
